<?php

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        //permisos para cursos
        DB::table('permissions')->insert([
            'name'=>'role-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'role-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'role-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'role-delete',
        ]);
        /* permisos para roles */
        DB::table('permissions')->insert([
            'name'=>'product-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'product-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'product-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'product-delete',
        ]);
        //permisos para categoria
        DB::table('permissions')->insert([
            'name'=>'category-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'category-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'category-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'category-delete',
        ]);
        //permisos para transacciones
        DB::table('permissions')->insert([
            'name'=>'transaction-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'transaction-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'transaction-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'transaction-delete',
        ]);
        //permisos para not_availables
        DB::table('permissions')->insert([
            'name'=>'not_available-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'not_available-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'not_available-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'not_available-delete',
        ]);
        //permisos para details
        DB::table('permissions')->insert([
            'name'=>'details-list',
        ]);
        DB::table('permissions')->insert([
            'name'=>'details-create',
        ]);
        DB::table('permissions')->insert([
            'name'=>'details-edit',
        ]);
        DB::table('permissions')->insert([
            'name'=>'details-delete',
        ]);
        
        //dando un rool root a un usuario con id:1
        DB::table('model_has_roles')->insert([

            'model_type'=>'App\User',
            'role_id'=>'1',
            'model_id'=>'1',
        ]); 
        //dando permisos a un rol root con role_id:1
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'1',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'2',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'3',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'4',
            'role_id'=>'1'
        ]);
        //--------------------------------------
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'5',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'6',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'7',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'8',
            'role_id'=>'1'
        ]);
        //--------------------------------------
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'9',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'10',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'11',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'12',
            'role_id'=>'1'
        ]);   
        //------------------------------------------
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'13',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'14',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'15',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'16',
            'role_id'=>'1'
        ]); 
        ///---------------------------------------------
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'17',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'18',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'19',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'20',
            'role_id'=>'1'
        ]); 
        //----------------------------------------------
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'21',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'22',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'23',
            'role_id'=>'1'
        ]);
        DB::table('role_has_permissions')->insert([
            'permission_id'=>'24',
            'role_id'=>'1'
        ]);  

    }
}
